# -*- coding: utf-8 -*-
"""q3_c_karate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lLZS6etm1-RTHsHE35Zk49KxYvIRhvSk
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/SMA_A1/
#%cd /content/drive/MyDrive/Semester_3/SMA/

!pip install igraph

import igraph

#the graph is read in gml format
temp_graph = igraph.read("karate.gml")

#We have calculated the edgelist here
edges = temp_graph.get_edgelist()

!pip install networkx
import networkx as nx

our_graph = nx.Graph(edges) 
print(our_graph)

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt

# %matplotlib inline

# visualize the graph
nx.draw(our_graph, with_labels = True)


import networkx as nx
nx.__version__

print(nx.info(our_graph))

# start of spectral clustering

# create the adjacency matrix
adj_mat = nx.adjacency_matrix(our_graph)
print(adj_mat.todense())

import numpy as np

# now create the degree matrix
deg_mat = np.diag(np.sum(np.array(adj_mat.todense()), axis=1))
print('degree matrix:')
print(deg_mat)

# Here's the laplacian matrix
our_laplace_mat = deg_mat - adj_mat
print('laplacian matrix:')
print(our_laplace_mat)

eigen_val, eigen_vector = np.linalg.eig(our_laplace_mat)
# here are the eigenvalues of the Laplacian matrix
print('eigenvalues:')
print(eigen_val)
# here are the eigenvectors of the Laplacian matrix
print('eigenvectors:')
print(eigen_vector)

# sort the eigenvalues & eigenvectors on the basis of eigen values
eigen_vector = eigen_vector[:,np.argsort(eigen_val)]
eigen_val = eigen_val[np.argsort(eigen_val)]

print(eigen_vector)



clusters = v[:,1] > 0

#the number of clusters are returned
print(len(clusters))

new_list = np.array(clusters)
l1= new_list.tolist()
print(l1)

c0 = []
c1 = []

#the cluster belonging relation existence of each nodes are shown
for index, node in enumerate(l1):
  ele = node[0]
  print(index, ele)

#the two separate clusters are grouped accordingly
for index, node in enumerate(l1):
  if node[0]:
    c0.append(index)
  else:
    c1.append(index)

print(c0)

print(c1)